<div id="vue-test">
    <h1 id="app"> {{message}} </h1>
</div>

<script>
    require(['vue'], function(creatApp) {
        'use strict'
        const {
            createApp,
            ref
        } = Vue

        createApp({
            setup() {
                const message = ref('Hello vue!')
                return {
                    message
                }
            }
        }).mount('#app')
    })
</script>